Setup authors/users for demo purposes
CowboyDevOps/ChoppingBlogs pull request #9
Opened 2022-12-18 01:34 UTC by ayanlea

basic setup for users and authors

2022-12-18 05:03 UTC, kinkeadian25 requested changes

2022-12-18 05:03 UTC, kinkeadian25 commented on API/Controllers/UsersController.cs
> +}
same as other controller

2022-12-18 05:03 UTC, kinkeadian25 commented on Persistence/Persistence.csproj
> +      <PrivateAssets>all</PrivateAssets>
want to be careful about package references

2023-01-03 18:17 UTC, ayanlea commented
no longer needed

2023-01-03 18:17 UTC, closed without merging